In [1]:
import numpy

In [2]:
import numpy as np

Question1


In [3]:
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

Question2


In [ ]:
data1 = []
data2 = []
print("enter 5 values of data1:")
for i in range(5):
    temp =int(input())
    data1.append(temp)
print("enter 5 values of data2:")
for i in range(5):
    temp =int(input())
    data2.append(temp) 
arr1 = np.array(data1)
arr2 = np.array(data2)
arr3 = np.concatenate((arr1,arr2), axis=0)
arr3.sort()
arr3

Question3

In [8]:
arr = np.array( [[ 1, 2, 3], [ 4, 2, 5]] )
print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


Question4

In [7]:
a = np.array([1, 2, 3, 4, 5, 6])
a2 = a[np.newaxis, :]
row_vector = a[np.newaxis, :]
col_vector = a[:, np.newaxis]
a.shape,a2.shape,row_vector.shape,col_vector.shape

((6,), (1, 6), (1, 6), (6, 1))

In [6]:
a_1d_array = np.array([1, 2, 3, 4])
print("one dimensional array")
print(a_1d_array)
print("twodimensional array")
reshaped_to_2d = np.reshape(a_1d_array, (-1, 2))
print(reshaped_to_2d)

one dimensional array
[1 2 3 4]
twodimensional array
[[1 2]
 [3 4]]


Question5

In [5]:

a = np.array([[1, 2], 
              [3, 4]]) 
b = np.array([[5, 6], 
              [7, 8]]) 
print("Vertical stacking:\n", np.vstack((a, b))) 
  
print("\nHorizontal stacking:\n", np.hstack((a, b)))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


Question6

In [4]:
input_list = [int(item) for item in input("Enter the list items : ")]
   
new_set = set(input_list) 
print("No of unique items in the list are:", len(new_set))

Enter the list items : 20
No of unique items in the list are: 2
